### ISSUE TITLE
Black boxes

### ISSUE THREAD

**Issue by vmario89** [evbernardes/Origami_Patterns#1]
Hi,
stumbled upon your project some minutes ago and tried this out whith InkScape 1.0 and InkScape 1.1dev. For unkown reason i dotn get it to work on Windows 10. For each extension i get the following error when previewing or applying:

![grafik](https://user-images.githubusercontent.com/5631071/88821333-d2e05800-d1c2-11ea-9bbf-f28c01640633.png)

sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='nul' mode='w' encoding='cp1252'>

I dont know from where it comes

**Comment by vmario89** [comment]
fixed this by removing 

- the line with /dev/tty
stroke-dasharray having negative values.

See PR

**Comment by evbernardes** [comment]
Hello! Thanks for being interested!
Yes I ended up finding the problem with the dash arrays. For some reason the negative values worked before inkscape 1.0 with python 2 but they didn't work any longer when they changed to python 3.

I fixed it some days ago on my original project.
