### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vmario89** [evbernardes/Origami_Patterns#3]
Hi,

this project is really cool. Do you plan to give some license for it like MIT, GPL or whatever?

regards, Mario

**Comment by evbernardes** [comment]
Hey there! I haven't really thought about it, I'm mostly using it as a tool for my PhD thesis project. I will read more about licenses since I'm not an expert on them.

**Comment by evbernardes** [comment]
Done, it is now has an MIT license :)
